name: Smoke Tests

on:
  push:
    branches:
      - main
  pull_request:
    types:
    - opened
    - synchronize
    - reopened

jobs:
  syntax-test:
    runs-on: ubuntu-latest
    name: Syntax Test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: eliotsykes/rspec-rails-examples
          path: examples/
      - uses: ./
        id: split-tests
        name: Run this action
        with:
          glob: examples/spec/**/*_spec.rb
          split-total: 5
          split-index: 2
      - run: echo "The output test suite is ${{ steps.split-tests.outputs.test-suite }}"

  smoke-test-default:
    runs-on: ubuntu-latest
    name: Smoke Test Default
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: eliotsykes/rspec-rails-examples
          path: examples/
      - uses: ./
        id: split-tests
        name: Run this action
        with:
          glob: examples/spec/**/*_spec.rb
          split-total: 5
          split-index: 0
      - run: echo "The output test suite is ${{ steps.split-tests.outputs.test-suite }}"

  smoke-test-line:
    runs-on: ubuntu-latest
    name: Smoke Test Line Count
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: eliotsykes/rspec-rails-examples
          path: examples/
      - uses: ./
        id: split-tests
        name: Run this action
        with:
          line-count: true
          glob: examples/spec/**/*_spec.rb
          split-total: 5
          split-index: 1
      - run: echo "The output test suite is ${{ steps.split-tests.outputs.test-suite }}"

  smoke-test-junit:
    runs-on: ubuntu-latest
    name: Smoke Test JUnit
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: eliotsykes/rspec-rails-examples
          path: examples/
      - uses: ./
        id: split-tests
        name: Run this action
        with:
          junit-path: examples/
          glob: examples/spec/**/*_spec.rb
          split-total: 5
          split-index: 1
      - run: echo "The output test suite is ${{ steps.split-tests.outputs.test-suite }}"
